#!/bin/bash
# Copyright (C) 2018 Jaan Toots <jaan@jaantoots.org>

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

#------------------------------------------------------------------------

source ~/.config/i3blocks/environment

DISP="${BLOCK_INSTANCE}"

STEP="${1:-5}"

#------------------------------------------------------------------------

backlight() {
    xbacklight ${DISP:+-display ${DISP}} -get | head -1
}

toggle() {
    case "$(printf "%.0f" $(backlight))" in
        0|1)
            xbacklight ${DISP:+-display ${DISP}} -set 100
            ;;
        *)
            xbacklight ${DISP:+-display ${DISP}} -set 1
    esac
}

format() {
    read BACKLIGHT || exit
    printf "${backlight_icon} %.0f%%\n" $BACKLIGHT
    printf "%.0f%%\n" $BACKLIGHT
    echo
}

#------------------------------------------------------------------------

case $BLOCK_BUTTON in
  3) toggle ;;  # right click, max/min
  4) xbacklight ${DISP:+-display ${DISP}} -time 50 -dec $STEP ;; # scroll down, decrease
  5) xbacklight ${DISP:+-display ${DISP}} -time 50 -inc $STEP ;; # scroll up, increase
esac

backlight | format
