#!/bin/bash
# Copyright (C) 2018 Jaan Toots <jaan@jaantoots.org>

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

#------------------------------------------------------------------------

source ~/.config/i3blocks/environment

HIGH="${1:-70}"
CRITICAL="${2:-85}"
URGENT="${3:-95}"

#------------------------------------------------------------------------

format() {
    read TEMP
    TEMP=$(($TEMP/1000))
    ICON=${temp_icons[$(echo $TEMP | awk 'BEGIN {OFMT="%d";}
        {print $1 >= 40 ? ($1 < 90 ? ($1 - 40)/10 : 4) : 0;}')]}
    COLOR=
    if [[ $TEMP -ge $CRITICAL ]]; then
        COLOR="$base08"
    elif [[ $TEMP -ge $HIGH ]]; then
        COLOR="$base0A"
    fi
    echo "$ICON $TEMP°C"
    echo "$TEMP°C"
    echo "$COLOR"
}

#------------------------------------------------------------------------

cat /sys/devices/platform/coretemp.0/hwmon/hwmon?/temp1_input | head -1 | format
if [[ $TEMP -ge $URGENT ]]; then
    exit 33
fi
