#!/bin/bash
# Copyright (C) 2014 Julien Bonjean <julien@bonjean.info>
# Copyright (C) 2014 Alexander Keller <github@nycroth.com>
# Copyright (C) 2018 Jaan Toots <jaan@jaantoots.org>

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

#------------------------------------------------------------------------

source ~/.config/i3blocks/environment

MIXER="default"
[[ -n "$(lsmod | grep pulse)" ]] && MIXER="pulse"
[[ -n "$(lsmod | grep jack)" ]] && MIXER="jackplug"
MIXER="${2:-$MIXER}"

SCONTROL="${BLOCK_INSTANCE:-$(amixer -D $MIXER scontrols |
    sed -n "s/Simple mixer control '\([A-Za-z ]*\)',0/\1/p" |
    head -n1
)}"

STEP="${1:-5%}"

#------------------------------------------------------------------------

capability() { # Return "Capture" if the device is a capture device
    amixer -D $MIXER get $SCONTROL |
        sed -n "s/  Capabilities:.*cvolume.*/Capture/p"
}

volume() {
    amixer -D $MIXER get $SCONTROL $(capability)
}

format() {
    sed_filter='s/.*\[([0-9]+%)\] (\[(-?[0-9]+.[0-9]+dB)\] )?\[(on|off)\]/'
    # If dB was selected, print that instead
    sed_filter+="$([[ "$STEP" = *dB ]] && echo '\3' || echo '\1')"
    sed_filter+=' \4/p'
    sed -nE "$sed_filter" | head -n1 | fancy_format
}

fancy_format() {
    read VOL STATE
    COLOR=
    ICON="${volume_icons[0]}"
    case "$STATE" in
        on)
            ICON="${volume_icons[2]}"
            if [[ "$VOL" = *% ]] && [[ "${VOL%\%}" -lt 33 ]]; then
                ICON="${volume_icons[1]}"
            fi
            ;;
        off)
            COLOR="$base0A"
            ;;
        *)
            COLOR="$base08"
    esac
    echo "$ICON $VOL"
    echo "$VOL"
    echo "$COLOR"
}

#------------------------------------------------------------------------

case $BLOCK_BUTTON in
  3) amixer -q -D $MIXER sset $SCONTROL $(capability) toggle ;;  # right click, mute/unmute
  4) amixer -q -D $MIXER sset $SCONTROL $(capability) ${STEP}- ;; # scroll down, decrease
  5) amixer -q -D $MIXER sset $SCONTROL $(capability) ${STEP}+ ;; # scroll up, increase
esac

volume | format
