#!/bin/bash
# Copyright (C) 2014 Alexander Keller <github@nycroth.com>
# Copyright (C) 2018 Jaan Toots <jaan@jaantoots.org>

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

#------------------------------------------------------------------------

source ~/.config/i3blocks/environment

INTERFACE="${BLOCK_INSTANCE}"
if [[ -z $INTERFACE ]]; then
    for iface in /sys/class/net/wl*; do
        [[ -d ${iface}/wireless ]] && INTERFACE=$(basename $iface) && break
    done
fi

[[ -n $INTERFACE ]] && [[ -d /sys/class/net/${INTERFACE}/wireless ]] || exit

#------------------------------------------------------------------------

IFS=$'\n' read -d '' ESSID FREQ BITR < <(iwconfig $INTERFACE | sed -nE '
    s/.*ESSID:"(.*)".*/\1/p
    s/.*Frequency:([0-9]+(\.[0-9]+)? \S+).*/\1/p
    s/.*Bit Rate=([0-9]+(\.[0-9]+)? \S+).*/\1/p')
COLOR="$base08"
if [[ "$(cat /sys/class/net/$INTERFACE/operstate)" = "up" ]]; then
    COLOR="$base0B"
    IP="$(ip addr show $INTERFACE |
        sed -nE 's/\s*inet6? ([^\/]+)\/.*/\1/p' | head -1)"
fi
echo "${wifi_icon}"\
    "${IP:+ }${IP}${ESSID:+ }${ESSID}${FREQ:+ }${FREQ}${BITR:+ }${BITR}"
echo "$ESSID"
echo "$COLOR"
