syntax enable

" load indent files
filetype plugin indent on
" Makefiles need actual tabs
autocmd FileType make set tabstop=8 shiftwidth=8 noexpandtab
" use spaces instead of tabs
set tabstop=4 shiftwidth=4 expandtab smarttab

" show line numbers
set number

" highlight current line
set cursorline

" visual autocomplete
set wildmenu

" better search
set incsearch hlsearch
nnoremap <leader><space> :nohlsearch<CR>

" use .vimrc_background generated by base16-shell
if filereadable(expand("~/.vimrc_background"))
    let base16colorspace=256
    source ~/.vimrc_background
endif
