#!/usr/bin/perl

use strict;
use warnings;

my $BAT_UNK_SYMBOL = $ENV{BAT_UNK_SYMBOL} || '';
my $BAT_CHARGING_SYMBOL = $ENV{BAT_CHARGING_SYMBOL} || '';
my $BAT_FULL_SYMBOL = $ENV{BAT_FULL_SYMBOL} || '';
my @BAT_SYMBOL = (
    $ENV{BAT_0_SYMBOL} || '',
    $ENV{BAT_1_SYMBOL} || '',
    $ENV{BAT_2_SYMBOL} || '',
    $ENV{BAT_3_SYMBOL} || '',
    $ENV{BAT_4_SYMBOL} || ''
);
my $BAT_FULL_COLOR = $ENV{BAT_FULL_COLOR} || $ENV{_base0B} || "";
my $BAT_LOW_COLOR = $ENV{BAT_LOW_COLOR} || $ENV{_base0A} || "";
my $BAT_CRITICAL_COLOR = $ENV{BAT_CRITICAL_COLOR} || $ENV{_base08} || "";
my $BAT_LOW = $ENV{BAT_LOW} || 25;
my $BAT_CRITICAL = $ENV{BAT_CRITICAL} || 15;
my $BAT_URGENT = $ENV{BAT_URGENT} || 10;

my $instance = $ENV{instance} || "BAT0";
my $path = "/sys/class/power_supply/$instance";

sub read_value {
    open(my $fh, "<", $_[1]) or return undef;
    $_[0] = <$fh>;
    close($fh)
}

my $status;
my $capacity;
my $charge_full;
my $charge_now;
my $current_now;
my $voltage_now;
read_value($status, "$path/status") or die;
read_value($capacity, "$path/capacity") or die;
read_value($charge_full, "$path/charge_full")
    or read_value($charge_full, "$path/energy_full") or die;
read_value($charge_now, "$path/charge_now")
    or read_value($charge_full, "$path/energy_full") or die;
read_value($voltage_now, "$path/voltage_now") or die;
unless (read_value($current_now, "$path/current_now")) {
    unless (read_value($current_now, "$path/power_now")) {
        $current_now = 0;
    }
    $voltage_now = 1e6;
}

my $icon = $BAT_UNK_SYMBOL;
my $color = "";
my $time = 0;
if ($status =~ /Charging/ and $current_now > 0) {
    $icon = $BAT_CHARGING_SYMBOL;
    $time = 3600*($charge_full - $charge_now)/$current_now;
}
elsif ($status =~ /Full/) {
    $icon = $BAT_FULL_SYMBOL;
    $color = $BAT_FULL_COLOR;
}
elsif ($status =~ /Discharging/ and $current_now > 0) {
    $icon = $BAT_SYMBOL[int(($capacity + 12)/25)];
    $time = 3600*$charge_now/$current_now;
    if ($capacity <= $BAT_CRITICAL) { $color = $BAT_CRITICAL_COLOR; }
    elsif ($capacity <= $BAT_LOW) { $color = $BAT_LOW_COLOR; }
}

my $percent = ($charge_full > 0) ? 100*$charge_now/$charge_full : 0;
my $power = $voltage_now*$current_now/1e12;
my $full_text;
if ($time) {
    $full_text = sprintf("%s %.2f%% %02d:%02d %.1fW",
        $icon, $percent, $time/3600, ($time % 3600)/60, $power);
} else {
    $full_text = sprintf("%s %.2f%%", $icon, $percent);
}
my $short_text = sprintf("%.2f", $percent);

printf("%s\n%s\n%s\n", $full_text, $short_text, $color);
if ($percent < $BAT_URGENT) { exit(33); }
exit(0);
