#!/bin/bash

set -e

AUDIO_HIGH_SYMBOL=${AUDIO_HIGH_SYMBOL:-''}
AUDIO_MED_SYMBOL=${AUDIO_MED_SYMBOL:-''}
AUDIO_LOW_SYMBOL=${AUDIO_LOW_SYMBOL:-''}
AUDIO_MUTED_SYMBOL=${AUDIO_MUTED_SYMBOL:-''}
AUDIO_MUTED_COLOR=${AUDIO_MUTED_COLOR:-$_base0A}
AUDIO_MED_THRESH=${AUDIO_MED_THRESH:-30}
AUDIO_LOW_THRESH=${AUDIO_LOW_THRESH:-0}
AUDIO_DELTA=${AUDIO_DELTA:-5}

_get_dump() {
    default_sink=$(pactl info | grep -m1 -Po "^Default Sink: \K\S+")
    sinks=$(pactl list short sinks | cut -f2)
    next_sink=$(sed -n '/^'"$default_sink"'$/{n;p;q}' <<<"$sinks")
    prev_sink=$(sed -n '/^'"$default_sink"'$/{x;p;q};h' <<<"$sinks")
    default_sink_info=$(pactl list sinks | grep -Po "^\s+(Name|Mute|Volume): \K.*" | grep -A2 -xF "$default_sink" | tail +2)
    mute=$(head -1 <<<"$default_sink_info")
    volume=$(tail +2 <<<"$default_sink_info" | grep -Po '\d+%' | head -1 | tr -d '%')
}

_handle_click() {
    case $button in
        1) jq -r '.[]' <<<"$modifiers" | grep -q Mod4 && pactl set-default-sink "${next_sink:-$(head -1 <<<"$sinks")}" ;;&
        2) pactl set-sink-mute "$default_sink" toggle ;;&
        3) jq -r '.[]' <<<"$modifiers" | grep -q Mod4 && pactl set-default-sink "${prev_sink:-$(tail -1 <<<"$sinks")}" ;;&
        4) pactl set-sink-volume "$default_sink" -"$AUDIO_DELTA"% ;;&
        5) pactl set-sink-volume "$default_sink" +"$AUDIO_DELTA"% ;;&
        ?) _get_dump ;;
    esac
}

_get_dump
_handle_click

icon=$AUDIO_HIGH_SYMBOL
color=
[ "$volume" -le "$AUDIO_MED_THRESH" ] && icon=$AUDIO_MED_SYMBOL
[ "$volume" -le "$AUDIO_LOW_THRESH" ] && icon=$AUDIO_LOW_SYMBOL
[ "$mute" = "yes" ] && icon=$AUDIO_MUTED_SYMBOL && color=$AUDIO_MUTED_COLOR

printf '%s\n%s\n%s\n' "$icon $volume%" "$volume%" "$color"
#printf '{"full_text": "%s", "short_text": "%s", "color": "%s"}\n' "$icon $volume%" "$volume%" "$color"
