#!/bin/sh

# Called by sxiv(1) whenever an image gets loaded.
# The output is displayed in sxiv's status bar.
# Arguments:
#   $1: path to image file
#   $2: image width
#   $3: image height

s=" | " # field separator

exec 2>/dev/null

filename=$(basename -- "$1")
filesize=$(du -Hh -- "$1" | cut -f 1)

exif=$(exiv2 "$1")
geometry="${2}x${3}"

exif () {
    echo -n $(grep -s -m 1 "$1" <<<"$exif" | cut -d ':' -f 2 | cut -c 2-)
}

focal=$(exif "Focal length")
exposure=$(exif "Exposure time")
aperture=$(exif "Aperture")
iso=$(exif "ISO speed")

echo "${filesize}${s}${geometry}${s}${focal}${s}${exposure}${s}${aperture}${s}${iso}${s}${filename}"
