#!/bin/bash

# Called by sxiv(1) whenever an image gets loaded.
# The output is displayed in sxiv's status bar.
# Arguments:
#   $1: path to image file
#   $2: image width
#   $3: image height

s=" | " # field separator

exec 2>/dev/null

filename=$(basename -- "$1")
filesize=$(du -Hh -- "$1" | cut -f 1)

exif=$(exiftool -c '%.6f' -d '%F %T' "$1")

exif () {
    echo -n $(grep -s -m 1 -e "^$1\s*:" <<<"$exif" | cut -d ':' -f 2- | cut -c 2-)
}

focal="$(exif "Focal Length")"
exposure="$(exif "Exposure Time")"
aperture="$(exif "F Number")"
iso="$(exif "ISO")"
gps="$(exif "GPS Position")"
date="$(exif "Date/Time Original")"

if [ -z "$date" ]; then
    date="$(date --date="@$(stat -c '%Y' "$1")" +'%F %T')"
fi

geometry="${2}x${3}"
if [ -z "$2" ]; then
    geometry="$(exif "Image Size")"
fi

echo "${filesize}${s}${geometry}${focal:+$s}${focal}${exposure:+$s}${exposure}${aperture:+${s}F}${aperture}${iso:+${s}ISO }${iso}${gps:+$s}${gps}${date:+$s}${date}${s}${filename}"
