# UI
zoom.default: 200%
fonts.monospace: monospace
fonts.completion.category: bold 12pt monospace
fonts.completion.entry: 12pt monospace
fonts.debug_console: 10pt monospace
fonts.downloads: 10pt monospace
fonts.hints: 10pt monospace
fonts.keyhint: 10pt monospace
fonts.messages.error: 12pt monospace
fonts.messages.info: 12pt monospace
fonts.messages.warning: 12pt monospace
fonts.prompts: 12pt monospace
fonts.statusbar: 12pt monospace
fonts.tabs: 12pt monospace

# Misc
completion.cmd_history_max_items: -1
scrolling.bar: when-searching
scrolling.smooth: true

# Keybindings
bindings.commands:
    normal:
        zl:  spawn --userscript qute-pass -d dmenu
        zol: spawn --userscript qute-pass -d dmenu --otp-only
        zpl: spawn --userscript qute-pass -d dmenu --password-only
        zul: spawn --userscript qute-pass -d dmenu --username-only
